FORMAT: 1A
HOST: https://iot-router.herokuapp.com/webapi

# iot-router

IOT-Router is api for retrieving list of mac addresses, which are connected 
to the wi-fi router. All operations use MacIp Object. It has following attributes:
+ deviceName - name of connected device. type: String
+ deviceMacAddress - mac address of connected device. type: String 

## MAC ADDRESSES [/]

## List All MAC Addresses [GET/houses/{house_id}/addresses]

returns all mac addresses and names, which are connected to router

+ Parameters
    + house_id (number) - ID of house

+ Response 200 (application/json)

        [
            {
                "deviceName": "USER-PC",
                "deviceMacAddress": "00:0a:95:9d:68:16",
                "mac_id": "qengimdsmf",
            },
            
            {
                "deviceName": "USER2-PC",
                "deviceMacAddress": "01:0b:22:fd:18:1w",
                "mac_id": "asniasdanmsd"
            }
        ]
        
## Check if owner is at home [GET/houses/{house_id}/available]

returns true if owner is at home, false otherwise

+ Parameters
    + house_id (number) - ID of house

+ Response 200 (application/json)

        {
            "atHome": true
        }


## Connect To Router [POST/houses/{house_id}/connect]

You can connect to router by post method. It returns response code 200 if successfull
and id of object after creation. returns code 401 if it fails.

+ Parameters
    + house_id (number) - ID of house

+ Request (application/json)

        {
            "deviceName": "USER-PC",
            "deviceMacAddress": "00:0a:95:9d:68:16"
        }

+ Response 200 (application/json)
        {
            "deviceName": "USER-PC",
            "deviceMacAddress": "00:0a:95:9d:68:16",
            "mac_id": zxcqrqwr
        }
+ Response 401 (application/json)

### Disconnect From Router [DELETE/houses/{house_id}/connect/{mac_id}]

You can disconnect from router by delete method. It returns 200 if successfull
and 401 if it fails

+ Request (application/json)

        {
            "deviceName": "USER-PC",
            "deviceMacAddress": "00:0a:95:9d:68:16",
        }

+ Response 200 (application/json)
+ Response 401 (application/json)

## ping [/ping]
Returns 200 if server is running, 400 if not
### Ping [GET]
+ Response 200 (application/plain)
+ Response 400 (application/plain)