FORMAT: 1A
HOST: https://iot-router.herokuapp.com/webapi

# iot-router

IOT-Router is api for retrieving list of mac addresses, which are connected 
to the wi-fi router. All operations use MacIp Object. It has following attributes:
+ deviceName - name of connected device. type: String
+ deviceMacAddress - mac address of connected device. type: String 

## MAC ADDRESSES [/addresses]

### List All MAC Addresses [GET]

returns all mac addresses and names, which are connected to router

+ Response 200 (application/json)

        [
            {
                "deviceName": "USER-PC",
                "deviceMacAddress": "00:0a:95:9d:68:16",
            }
        ]

### Connect To Router [POST]

You can connect to router by post method. It returns 200 if successfull
and 401 if it fails

+ Request (application/json)

        {
            "deviceName": "USER-PC",
            "deviceMacAddress": "00:0a:95:9d:68:16",
        }

+ Response 200 (application/json)
+ Response 401 (application/json)

### Disconnect From Router [DELETE]

You can disconnect from router by delete method. It returns 200 if successfull
and 401 if it fails

+ Request (application/json)

        {
            "deviceName": "USER-PC",
            "deviceMacAddress": "00:0a:95:9d:68:16",
        }

+ Response 200 (application/json)
+ Response 401 (application/json)